### ISSUE TITLE
Poder copiar el detalle de un error

### ISSUE THREAD

**Issue by gobstones-issues** [gobstones/gobstones-issues#11]
Como alumno podría querer copiar la descripción del error que me sale en el programa para enviarlo por mail a un compañero o profesor sin necesidad de pasarle el código, solo el error que me sale, por ahora no es posible copiarlo y pegarlo, solo se puede capturar un print screen
----------
Email: vdecristofolo@yahoo.com.ar
URL: https://gobstones.github.io/gobstones-sr/
Project: Ejemplo1

**Comment by fidel-ml** [comment]
El mensaje de error se puede copiar desde la pantalla de Boom (no así desde la burbuja que aparece en el bloque que lo produce).
