### ISSUE TITLE
error cargndo...

### ISSUE THREAD

**Issue by gobstones-issues** [gobstones/gobstones-issues#26]
No me descarga el proyecto  “Supermimo multiplica” 
----------
Email: ?
URL: https://gobstones.github.io/gobstones-jr/?course=program-ar/proyectos-gobstones-jr&github=program-ar/proyectos-gobstones-jr&path=Proyectos/Cap.4/404.Super+mimo+multiplica
Project: Nuevo proyecto

**Comment by fidel-ml** [comment]
No puedo reproducir el error, y no se brinda suficiente información del contexto de uso (navegador, tipo de error, etc.) como para descubrir de qué error se trata. Tampoco cuento con información de contacto para saber a quién preguntarle...
