### ISSUE TITLE
No se cambia al ingles "Nuevo proyecto"

### ISSUE THREAD

**Issue by gobstones-issues** [gobstones/gobstones-issues#28]
"Nuevo proyecto" no cambia de idioma al elegir ingles
----------
Email: ?
URL: https://gobstones.github.io/gobstones-sr/
Project: Nuevo proyecto

**Comment by fidel-ml** [comment]
El reporte del supuesto error no explica qué es lo que se supone que está mal. Debería al menos haber información acerca de qué es lo que sucede, y qué es lo que se espera que suceda, para que podamos encontrar el origen del supuesto error.
En las pruebas realizadas, el entorno realizó los cambios programados sin problemas.
Quizás el reporte haga alusión a que hay partes que son propias de los proyectos, y esas partes conservan el idioma en el que fueron programadas, independientemente del idioma del entorno... Esa "internacionalización" de proyectos está en la lista de deseos a futuro.
