### ISSUE TITLE
Variantes en "Quiero Retruco!"

### ISSUE THREAD

**Issue by gobstones-issues** [gobstones/gobstones-issues#37]
Entiendo que tanto Palo como NumeroDeCarta son Variantes, pero encuentro que el bloque de la Variante Palo esta en la sección "Valores Literales" y la Variante NumeroDeCarta está en "Funciones Primitivas". 

Mi sugerencia es que estén en la misma sección.
----------
Email: leonardo.volinier@gmail.com
URL: https://gobstones.github.io/gobstones-jr/?course=gobstones/curso-InPr-UNQ&github=gobstones/curso-InPr-UNQ&path=Proyectos/10.Registros/2.1.Quiero+retruco
Project: ¡Quiero retruco!

**Comment by gpfernandezflorio** [comment]
No aplica.
