### ISSUE TITLE
No carga los ejercicio de ninguno de los cursos en Jr

### ISSUE THREAD

**Issue by gobstones-issues** [gobstones/gobstones-issues#39]
Mensaje de error: "No se ha podido descargar el proyecto"
----------
Email: ?
URL: https://gobstones.github.io/gobstones-jr/?course=gobstones/curso-InPr-UNQ&github=gobstones/curso-InPr-UNQ&path=Proyectos/1.Descubrir+Gobstones/1.1.La+simulaci%C3%B3n+del+docente+robot
Project: Nuevo proyecto

**Comment by MartinLPE** [comment]
Buen dia! Cuando intentamos abrir un proyecto cualquiera en las maquinas de la institución, se abren bien en los 5 primeros equipos, a partir del 6to equipo me figura un cuadro de dialogo que me indica que no se ha podido abrir el proyecto, me ocurre esto independientemente de la secuencia de encendido de las maquinas. Podrían ayudarme con este problema ya que me resulta indispensable el uso de esta herramienta para poder cerrar el año con los contenidos programados? Desde ya agradeceré todo lo que puedan hacer. Les adjunto imagen del problema.
![WhatsApp Image 2021-09-22 at 12 52 47](https://user-images.githubusercontent.com/92927854/138279832-f86f1d2a-75c2-41b0-93c8-52d9e6b1a64e.jpeg)

**Comment by faloi** [comment]
¡Hola @MartinLPE! Soy parte del equipo de desarrollo de Gobstones y justamente estoy trabajando para resolver este problema, que tiene que ver con algunos cambios que hizo GitHub en sus políticas de uso.

Ya tenemos una solución implementada y está en fase de pruebas, pero pienso que podrías utilizarla en el aula (y de paso, nos ayudarías a confirmar que efectivamente funciona). Si te parece que podría servirte, podés unirte a nuestro servidor de Discord [haciendo clic acá](https://discord.gg/D9fdkvn5) o escribirme por mail a faloi@pm.me para que te cuente cómo acceder.

**Comment by faloi** [comment]
Esto quedó resuelto con el deploy a producción de la versión [2.21.0](https://github.com/gobstones/gobstones-web/releases/tag/2.21.0), que utiliza el [activity-server](https://github.com/gobstones/gobstones-activity-server) para listar los recursos en GitHub.
