### ISSUE TITLE
ERROR DE LA PÁGINA GOBSTONES

### ISSUE THREAD

**Issue by ALBERTPROF** [gobstones/gobstones-issues#71]
Buenas, hace algunos día que el curso program-ar/proyectos-gobstones-jr
( https://gobstones.github.io/gobstones-jr/?course=program-ar/proyectos-gobstones-jr)  al ingresar a cada ejercicio sale el mensaje de error  "No se ha podido descargar el proyecto" y no deja cargar la plantilla del ejercicio, he probado desde distintos exploradores y siempre sale lo mismo. Aguardo su respuesta. Gracias!

**Comment by fidel-ml** [comment]
Estamos trabajando en el tema. Es un problema de los servicios que utilizamos para tal descarga.
Mientras seguimos buscando resolverlo, pueden volver a trabajar en forma off-line, descargando los ejercicios. Para ello, sigan el siguiente intructivo: https://docs.google.com/document/d/e/2PACX-1vRXa-LFyqFKBQTAGMkXwfnaGlyfzdbcktakH6Q1c6RL9fMORKi1CvS7SlmQWvhCgj213kuU0PbykeJX/pub

**Comment by fidel-ml** [comment]
Ya está resuelto el problema.
